#server.port = 80
#
##MySQL ?? ??
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/gift?serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=1251
#
##???? ?? ?? ??
#spring.jpa.properties.hibernate.show_sql=true
#
##???? ???? ??? ???? ?? ???
#spring.jpa.properties.hibernate.format_sql=true
#
##??? ???? ???? ??? ???? ??
#logging.level.org.hibernate.type.descriptor.sql=trace
#
#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
#
##Thymeleaf cache ?? ??
#spring.thymeleaf.cache=false
#
##google login
#spring.security.oauth2.client.registration.google.clientId=855672898277-etdr1q4vt4g77of84ua47e992k5po6hn.apps.googleusercontent.com
#spring.security.oauth2.client.registration.google.clientSecret=ZptsDAPoVjn7DzVYbzSDNt1v
server:
  port: 80
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gift?serverTimezone=Asia/Seoul
    username: root
    password: 1251


  thymeleaf:
    prefix : classpath:templates/
    suffix : .html
    cache : false

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google: # /oauth2/authorization/google ? ??? ???? ??.
            client-id: 855672898277-etdr1q4vt4g77of84ua47e992k5po6hn.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile


